version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: chatting-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - $HOME/study/data/.mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=chatting